# Generated by Django 6.0.5 on 2026-05-28 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('kp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_ru', models.CharField(max_length=500)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('rating_kp', models.FloatField(blank=True, null=True)),
                ('rating_imdb', models.FloatField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('watched', 'Просмотрено'), ('watchlist', 'Буду смотреть')], max_length=20)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('watched_date', models.CharField(blank=True, max_length=20, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('kp', models.ForeignKey(db_column='kp_id', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'user_movies',
                'unique_together': {('user_id', 'kp', 'status')},
            },
        ),
    ]
